version: '3.8'
services:

  groups:
    env_file:
      - .env
    build:
      context: ../../.
      dockerfile: local-setup/docker/groups.src.dockerfile
    environment:
      - MONGOURL=mongodb://mongo:27017
    networks:
      - apinet
    depends_on:
      - mongo

  users:
    env_file:
      - .env
    build:
      context: ../../.
      dockerfile: local-setup/docker/users.src.dockerfile
    environment:
      - MONGOURL=mongodb://mongo:27017
    networks:
      - apinet
    depends_on:
      - mongo

  mongo:
    build:
      context: .
      dockerfile: mongo.src.dockerfile
    environment:
      - MONGO_INITDB_DATABASE=SHIMBIR
    ports:
    - 47017:27017
    networks:
    - apinet
  
  webserver:
    build:
      context: ../../.
      dockerfile: local-setup/docker/local-nginx.dockerfile
    ports:
    - 30088:80
    networks:
    - apinet
    depends_on:
    - users
#    - groups
#    - sms
#    - calling
#    - frontend


networks:
  apinet: